# -*- coding: utf-8 -*-
"""yolo_v4_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WXPg6nD8p4RWBLaajggKsZFshoUNcjXK
"""

from google.colab import drive 
drive.mount ('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Yolo_v4

!git clone https://github.com/AlexeyAB/darknet

import os, fnmatch
import numpy as np

train_file = open("/content/drive/MyDrive/Yolo_v4/train.txt", "w")
valid_file = open("/content/drive/MyDrive/Yolo_v4/test.txt", "w")
listOfFiles = os.listdir('/content/drive/MyDrive/Yolo_v4/obj/')  
pattern = "*.jpg"  
for f_name in listOfFiles:  
  if fnmatch.fnmatch(f_name, pattern):
    if np.random.rand(1) < 0.8:
      train_file.write("/content/drive/MyDrive/Yolo_v4/obj/"+f_name+"\n")
      #print ("data/obj/"+f_name)
    else:
      valid_file.write("/content/drive/MyDrive/Yolo_v4/obj/"+f_name+"\n")  
      
train_file.close()
valid_file.close()

obj_data = """classes= 2
train  = /content/drive/MyDrive/Yolo_v4/train.txt
valid  = /content/drive/MyDrive/Yolo_v4/test.txt
names =  /content/drive/MyDrive/Yolo_v4/obj.names
backup = /content/drive/MyDrive/Yolo_v4/Training
"""

file = """text_file = open("/content/drive/MyDrive/Yolo_v4/obj.data", "w");text_file.write(obj_data);text_file.close()""" 

exec(file)

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Yolo_v4/darknet

!make

# yolov4 weights 
!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.conv.137

!./darknet detector train /content/drive/MyDrive/Yolo_v4/obj.data /content/drive/MyDrive/Yolo_v4/darknet/cfg/yolov4-custom.cfg /content/drive/MyDrive/Yolo_v4/darknet/yolov4.conv.137 -dont_show -map

import cv2 
import matplotlib.pyplot as plt

def imshow (path): 
  image = cv2.imread(path)
  height, width = image.shape[:2]
  resized_image = cv2.resize(image,(3*width, 3*height), interpolation = cv2.INTER_CUBIC)
  fig = plt.gcf()
  fig.set_size_inches(18, 10)
  plt.axis('off')
  plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
  plt.show()

!./darknet detector test /content/drive/MyDrive/Yolo_v4/obj.data /content/drive/MyDrive/Yolo_v4/darknet/cfg/yolov4-custom.cfg /content/drive/MyDrive/Yolo_v4/Training/yolov4-custom_last.weights /content/drive/MyDrive/Yolo_v4/obj/303-with-mask.jpg -thresh 0.3

imshow('predictions.jpg')